apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiodemo-v1
  labels:
    app: istiodemo
spec:
  selector:
    matchLabels:
      app: istiodemo
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: istiodemo
        version: v1
    spec:
      containers:
      - name: istiodemo
        image: tushpatt/istiodemo:latest
        ports:
        - containerPort: 8080       
         
