apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: tushpattistiodemo 
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: tushpattistiodemo 
    spec:
      containers:
        - name: tushpattistiodemo 
          image: tusharacr.azurecr.io/tushpattistiodemo
          ports:
          - containerPort: 80          
         
